### ISSUE TITLE
Error in Train.py

### ISSUE THREAD

**Issue by arcontechnologies** [xxj96/SQLNet#31]
?Seems that train.py generate errors. is there any pre-requisits
(

> base) C:\Users\Albel\Documents\SQLNet>python train.py --ca
> Loading from original dataset
> Loading data from %s data/train_tok.jsonl
> Loading data from %s data/train_tok.tables.jsonl
> Loading data from %s data/dev_tok.jsonl
> Loading data from %s data/dev_tok.tables.jsonl
> Loading data from %s data/test_tok.jsonl
> Loading data from %s data/test_tok.tables.jsonl
> Loading word embedding from %s glove/glove.42B.300d.txt
> Using fixed embedding
> Traceback (most recent call last):
>   File "train.py", line 57, in <module>
>     gpu=GPU, trainable_emb = args.train_emb)
>   File "C:\Users\Albel\Documents\SQLNet\sqlnet\model\sqlnet.py", line 43, in __init__
>     self.agg_pred = AggPredictor(N_word, N_h, N_depth, use_ca=use_ca)
>   File "C:\Users\Albel\Documents\SQLNet\sqlnet\model\modules\aggregator_predict.py", line 18, in __init__
>     dropout=0.3, bidirectional=True)
>   File "C:\Anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 425, in __init__
>     super(LSTM, self).__init__('LSTM', *args, **kwargs)
>   File "C:\Anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 52, in __init__
>     w_ih = Parameter(torch.Tensor(gate_size, layer_input_size))
> TypeError: new() received an invalid combination of arguments - got (float, int), but expected one of:
>  * (torch.device device)
>  * (torch.Storage storage)
>  * (Tensor other)
>  * (tuple of ints size, torch.device device)
>       didn't match because some of the arguments have invalid types: ([31;1mfloat[0m, [31;1mint[0m)
>  * (object data, torch.device device)
>       didn't match because some of the arguments have invalid types: ([31;1mfloat[0m, 

[31;1mint[0m)

**Comment by mikiihuang** [comment]
hi,I meet the same error as yours.Have you find out the solution to the error?Pls tell me.Thank you very much @arcontechnologies

**Comment by farsmile** [comment]
python2 or python3  
division is diffrent
is   a / 2   ==>  a // 2  work?

**Comment by LohitakshTrehan** [comment]
> hi,I meet the same error as yours.Have you find out the solution to the error?Pls tell me.Thank you very much @arcontechnologies

any solutions to it?
