### ISSUE TITLE
Problem when using it with dataset other than WikiSQL

### ISSUE THREAD

**Issue by tornadozou** [xxj96/SQLNet#39]
while i m running the train.py file with a dataset other than  WikiSQL. i  meet the error as follow:

Traceback (most recent call last):
  File "train.py", line 128, in <module>
    sql_data, table_data, TRAIN_ENTRY)
  File 
"/PyTorchWorker@h04f01267.nt12#0/sqlnet/utils.py", line 146, in epoch_train
    gt_where=gt_where_seq, gt_cond=gt_cond_seq, gt_sel=gt_sel_seq)
  File 
"/PyTorchWorker@h04f01267.nt12#0/sqlnet/model/sqlnet.py", line 141, in forward
    gt_where, gt_cond, reinforce=reinforce)
  File "/opt/conda/envs/python2.7/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File 
"/PyTorchWorker@h04f01267.nt12#0/sqlnet/model/modules/sqlnet_condition_predict.py", line 253, in forward
    cond_str_score[b, :, :, num:] = -100
IndexError: too many indices for tensor of dimension 3

Can anyone help?

**Comment by guotong1988** [comment]
……

**Comment by guotong1988** [comment]
I also can not solve it.

**Comment by dhs007** [comment]
Does it work perfectly with wikisql datasets?
